### ISSUE TITLE
Add remaining new members on Members page - Create section for  previous members in the same page

### ISSUE THREAD

**Issue by rubensmatosjr** [Morea-IFS/morea-ds-web#19]
Currently some members still do not appear in the Members page:

- Edvan
- Junior
- Anthony
- Felipe Lisboa

We should also have a section for previous members:

- Paula
- Adrielly
- Henrique
- Kauã
- Mariana

**Comment by Silas-Prog** [comment]
Add members' lattes resume in the members section.

**Comment by Alexandre-Michael** [comment]
active members added

**Comment by rubensmatosjr** [comment]
A tarefa já está completa? Se sim, fechemos ela.
