### ISSUE TITLE
Django default page not working 

### ISSUE THREAD

**Issue by Vineees** [Morea-IFS/morea-ds-web#43]
When I trying to login using the default admin page, server return 500 error

![image](https://github.com/Morea-IFS/morea-ds-web/assets/72805423/04d6fca3-8a1c-42d9-8689-940c139e396f)

Nothing on the server terminal.

**Comment by Vineees** [comment]
![image](https://github.com/Morea-IFS/morea-ds-web/assets/72805423/b4c109d5-5beb-4c90-b90e-4c247831a74a)

Looking for bugs I ended up finding files with the same name in the directory: app/migrations

I believe it shouldn't be like this.

**Comment by felipscarvalho** [comment]
> ![image](https://private-user-images.githubusercontent.com/72805423/339390491-b4c109d5-5beb-4c90-b90e-4c247831a74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MzQ1MDgsIm5iZiI6MTcxODgzNDIwOCwicGF0aCI6Ii83MjgwNTQyMy8zMzkzOTA0OTEtYjRjMTA5ZDUtNWJlYi00YzkwLWI5MGUtNGMyNDc4MzFhNzRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDIxNTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYTg4NjY4YzZmMWM0Y2ZiMDBiYmYxY2FhYTdhYzUzNDQyOWIwOTJkYzA5M2VmMjRmOWYyMDg0ODFlNDkyZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-FICxPfDCGdF0UvHLiH1WfPeLBl5LIF4n0Gp9_zdQ9Y)
> 
> Looking for bugs I ended up finding files with the same name in the directory: app/migrations
> 
> I believe it shouldn't be like this.

It should be solved now, please test this feature again.

**Comment by Vineees** [comment]
Starting deployment! Wait for more notes

**Comment by Vineees** [comment]
![image](https://github.com/Morea-IFS/morea-ds-web/assets/72805423/30b7db86-923c-4d3a-b528-a8f35c50d16d)

Deploy error, I believe this happened due to one of the problems listed.

**Comment by Vineees** [comment]
Solved!
