### ISSUE TITLE
Superuser creation not working 

### ISSUE THREAD

**Issue by Vineees** [Morea-IFS/morea-ds-web#46]
I don't know what is happening but I cant create a superuser, maybe can be login feature

![WhatsApp Image 2024-06-20 at 2 24 30 PM](https://github.com/Morea-IFS/morea-ds-web/assets/72805423/fbd0f148-ad3f-474c-b049-68086dfa51a3)

**Comment by felipscarvalho** [comment]
Please test fixes and give an feedback.

**Comment by Vineees** [comment]
Solved
